version: '3'
services:
        traefik:
                image: "traefik:v2.6"
                container_name: "traefik"
                command:
                        #- "--log.level=DEBUG"
                        - "--api.insecure=true"
                        - "--providers.docker=true"
                        - "--providers.docker.exposedbydefault=false"
                        - "--entrypoints.web.address=:8000"
                ports:
                        - "8000:8000"
                        - "8080:8080"
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        app:
                build: 
                        context: .
                        args:
                                - 'APP_ENV_FILE:app_nomysql.env'
                                      
                ports:
                        - 8000
                environment:
                        - NODB=TRUE
                labels:
                        - "traefik.enable=true"
                          #- "traefik.http.routers.app.rule=Host(`app.localhost`)"
                        - "traefik.http.routers.app.rule=PathPrefix(`/`)"
                        - "traefik.http.routers.app.entrypoints=web"
                logging:
                        driver: "fluentd"
                        options:
                                fluentd-address: 172.22.0.2:24224
                                tag: fluent
