version: '3'
services:
        'app':
                build: .
                ports:
                        - 10000:80
        'db':
                image: mysql
                env_file:
                        - db.env
                ports:
                        - 33066:3306
