version: '3'
services:
        'app':
                image: localhost:5000/djangotest
                ports:
                        - 8000:8000
                deploy: 
                        replicas: 1
        'db':
                image: mysql
                env_file:
                        - db.env
